services:
  scrapper:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_URL: ${DATABASE_URL}
      DISCORD_API_BASE_URL: ${DISCORD_API_BASE_URL}
      DISCORD_GUILD: ${DISCORD_GUILD}
      DISCORD_CHANNEL: ${DISCORD_CHANNEL}
    depends_on:
      - scrapper-db
    profiles: [production]
    networks:
      - ugc-net

  scrapper-db:
    image: postgres:16
    restart: always
    ports:
      - ${PORT_DB}:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    profiles: [production, dev]
    networks:
      - ugc-net

volumes:
  pgdata:

networks:
  ugc-net:
    driver: bridge
